apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    version: blue  # or green (switch manually or via pipeline)
  ports:
    - port: 80
      targetPort: 80
